package org.shiqing.ibd.model;

/**
 * An interface to represent an output spreadsheet java pojo.
 * This could be a result spreadsheet generated by analyzing IBD raw input spreadsheet or 
 * a second analyzing based on some generated analyze result.
 * 
 * @author shiqing
 *
 */
public interface OutputSpreadsheet {

}
