package org.shiqing.ibd.model;

/**
 * An interface to represent a spreadsheet java pojo.
 * This could be a raw spreadsheet from IBD or a result spreadsheet generated by the analyzer. 
 * 
 * @author shiqing
 *
 */
public interface Spreadsheet {

}
